/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manduchi
 */
public class STREAM_SETUPSetup extends DeviceSetup {

    /**
     * Creates new form STREAM_SETUPSetup
     */
    public STREAM_SETUPSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceButtons1 = new DeviceButtons();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        deviceField1 = new DeviceField();
        deviceField2 = new DeviceField();
        jPanel3 = new javax.swing.JPanel();
        deviceField3 = new DeviceField();
        deviceField4 = new DeviceField();
        jPanel4 = new javax.swing.JPanel();
        deviceField5 = new DeviceField();
        deviceField6 = new DeviceField();
        jPanel5 = new javax.swing.JPanel();
        deviceField7 = new DeviceField();
        deviceField8 = new DeviceField();
        jPanel6 = new javax.swing.JPanel();
        deviceField9 = new DeviceField();
        deviceField10 = new DeviceField();
        jPanel7 = new javax.swing.JPanel();
        deviceField11 = new DeviceField();
        deviceField12 = new DeviceField();
        jPanel8 = new javax.swing.JPanel();
        deviceField13 = new DeviceField();
        deviceField14 = new DeviceField();
        jPanel9 = new javax.swing.JPanel();
        deviceField15 = new DeviceField();
        deviceField16 = new DeviceField();
        jPanel10 = new javax.swing.JPanel();
        deviceField17 = new DeviceField();
        deviceField18 = new DeviceField();
        jPanel11 = new javax.swing.JPanel();
        deviceField19 = new DeviceField();
        deviceField20 = new DeviceField();
        jPanel12 = new javax.swing.JPanel();
        deviceField21 = new DeviceField();
        deviceField22 = new DeviceField();
        jPanel13 = new javax.swing.JPanel();
        deviceField23 = new DeviceField();
        deviceField24 = new DeviceField();
        jPanel14 = new javax.swing.JPanel();
        deviceField25 = new DeviceField();
        deviceField26 = new DeviceField();
        jPanel15 = new javax.swing.JPanel();
        deviceField27 = new DeviceField();
        deviceField28 = new DeviceField();
        jPanel16 = new javax.swing.JPanel();
        deviceField29 = new DeviceField();
        deviceField30 = new DeviceField();
        jPanel17 = new javax.swing.JPanel();
        deviceField31 = new DeviceField();
        deviceField32 = new DeviceField();

        setDeviceProvider("scdevail.rfx.local:8001");
        setDeviceTitle("Stream Setup");
        setDeviceType("STREAM_SETUP");
        setHeight(300);
        setWidth(800);
        getContentPane().add(deviceButtons1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(16, 1));

        deviceField1.setIdentifier("");
        deviceField1.setLabelString("Node:");
        deviceField1.setNumCols(30);
        deviceField1.setOffsetNid(2);
        jPanel2.add(deviceField1);

        deviceField2.setIdentifier("");
        deviceField2.setLabelString("Stream name:");
        deviceField2.setNumCols(30);
        deviceField2.setOffsetNid(3);
        deviceField2.setTextOnly(true);
        jPanel2.add(deviceField2);

        jPanel1.add(jPanel2);

        deviceField3.setIdentifier("");
        deviceField3.setLabelString("Node:");
        deviceField3.setNumCols(30);
        deviceField3.setOffsetNid(4);
        jPanel3.add(deviceField3);

        deviceField4.setIdentifier("");
        deviceField4.setLabelString("Stream name:");
        deviceField4.setNumCols(30);
        deviceField4.setOffsetNid(5);
        deviceField4.setTextOnly(true);
        jPanel3.add(deviceField4);

        jPanel1.add(jPanel3);

        deviceField5.setIdentifier("");
        deviceField5.setLabelString("Node:");
        deviceField5.setNumCols(30);
        deviceField5.setOffsetNid(6);
        jPanel4.add(deviceField5);

        deviceField6.setIdentifier("");
        deviceField6.setLabelString("Stream name:");
        deviceField6.setNumCols(30);
        deviceField6.setOffsetNid(7);
        deviceField6.setTextOnly(true);
        jPanel4.add(deviceField6);

        jPanel1.add(jPanel4);

        deviceField7.setIdentifier("");
        deviceField7.setLabelString("Node:");
        deviceField7.setNumCols(30);
        deviceField7.setOffsetNid(8);
        jPanel5.add(deviceField7);

        deviceField8.setIdentifier("");
        deviceField8.setLabelString("Stream name:");
        deviceField8.setNumCols(30);
        deviceField8.setOffsetNid(9);
        deviceField8.setTextOnly(true);
        jPanel5.add(deviceField8);

        jPanel1.add(jPanel5);

        deviceField9.setIdentifier("");
        deviceField9.setLabelString("Node:");
        deviceField9.setNumCols(30);
        deviceField9.setOffsetNid(10);
        jPanel6.add(deviceField9);

        deviceField10.setIdentifier("");
        deviceField10.setLabelString("Stream name:");
        deviceField10.setNumCols(30);
        deviceField10.setOffsetNid(11);
        deviceField10.setTextOnly(true);
        jPanel6.add(deviceField10);

        jPanel1.add(jPanel6);

        deviceField11.setIdentifier("");
        deviceField11.setLabelString("Node:");
        deviceField11.setNumCols(30);
        deviceField11.setOffsetNid(12);
        jPanel7.add(deviceField11);

        deviceField12.setIdentifier("");
        deviceField12.setLabelString("Stream name:");
        deviceField12.setNumCols(30);
        deviceField12.setOffsetNid(13);
        deviceField12.setTextOnly(true);
        jPanel7.add(deviceField12);

        jPanel1.add(jPanel7);

        deviceField13.setIdentifier("");
        deviceField13.setLabelString("Node:");
        deviceField13.setNumCols(30);
        deviceField13.setOffsetNid(14);
        jPanel8.add(deviceField13);

        deviceField14.setIdentifier("");
        deviceField14.setLabelString("Stream name:");
        deviceField14.setNumCols(30);
        deviceField14.setOffsetNid(15);
        deviceField14.setTextOnly(true);
        jPanel8.add(deviceField14);

        jPanel1.add(jPanel8);

        deviceField15.setIdentifier("");
        deviceField15.setLabelString("Node:");
        deviceField15.setNumCols(30);
        deviceField15.setOffsetNid(16);
        jPanel9.add(deviceField15);

        deviceField16.setIdentifier("");
        deviceField16.setLabelString("Stream name:");
        deviceField16.setNumCols(30);
        deviceField16.setOffsetNid(17);
        deviceField16.setTextOnly(true);
        jPanel9.add(deviceField16);

        jPanel1.add(jPanel9);

        deviceField17.setIdentifier("");
        deviceField17.setLabelString("Node:");
        deviceField17.setNumCols(30);
        deviceField17.setOffsetNid(18);
        jPanel10.add(deviceField17);

        deviceField18.setIdentifier("");
        deviceField18.setLabelString("Stream name:");
        deviceField18.setNumCols(30);
        deviceField18.setOffsetNid(19);
        deviceField18.setTextOnly(true);
        jPanel10.add(deviceField18);

        jPanel1.add(jPanel10);

        deviceField19.setIdentifier("");
        deviceField19.setLabelString("Node:");
        deviceField19.setNumCols(30);
        deviceField19.setOffsetNid(20);
        jPanel11.add(deviceField19);

        deviceField20.setIdentifier("");
        deviceField20.setLabelString("Stream name:");
        deviceField20.setNumCols(30);
        deviceField20.setOffsetNid(21);
        deviceField20.setTextOnly(true);
        jPanel11.add(deviceField20);

        jPanel1.add(jPanel11);

        deviceField21.setIdentifier("");
        deviceField21.setLabelString("Node:");
        deviceField21.setNumCols(30);
        deviceField21.setOffsetNid(22);
        jPanel12.add(deviceField21);

        deviceField22.setIdentifier("");
        deviceField22.setLabelString("Stream name:");
        deviceField22.setNumCols(30);
        deviceField22.setOffsetNid(23);
        deviceField22.setTextOnly(true);
        jPanel12.add(deviceField22);

        jPanel1.add(jPanel12);

        deviceField23.setIdentifier("");
        deviceField23.setLabelString("Node:");
        deviceField23.setNumCols(30);
        deviceField23.setOffsetNid(24);
        jPanel13.add(deviceField23);

        deviceField24.setIdentifier("");
        deviceField24.setLabelString("Stream name:");
        deviceField24.setNumCols(30);
        deviceField24.setOffsetNid(25);
        deviceField24.setTextOnly(true);
        jPanel13.add(deviceField24);

        jPanel1.add(jPanel13);

        deviceField25.setIdentifier("");
        deviceField25.setLabelString("Node:");
        deviceField25.setNumCols(30);
        deviceField25.setOffsetNid(26);
        jPanel14.add(deviceField25);

        deviceField26.setIdentifier("");
        deviceField26.setLabelString("Stream name:");
        deviceField26.setNumCols(30);
        deviceField26.setOffsetNid(27);
        deviceField26.setTextOnly(true);
        jPanel14.add(deviceField26);

        jPanel1.add(jPanel14);

        deviceField27.setIdentifier("");
        deviceField27.setLabelString("Node:");
        deviceField27.setNumCols(30);
        deviceField27.setOffsetNid(28);
        jPanel15.add(deviceField27);

        deviceField28.setIdentifier("");
        deviceField28.setLabelString("Stream name:");
        deviceField28.setNumCols(30);
        deviceField28.setOffsetNid(29);
        deviceField28.setTextOnly(true);
        jPanel15.add(deviceField28);

        jPanel1.add(jPanel15);

        deviceField29.setIdentifier("");
        deviceField29.setLabelString("Node:");
        deviceField29.setNumCols(30);
        deviceField29.setOffsetNid(30);
        jPanel16.add(deviceField29);

        deviceField30.setIdentifier("");
        deviceField30.setLabelString("Stream name:");
        deviceField30.setNumCols(30);
        deviceField30.setOffsetNid(31);
        deviceField30.setTextOnly(true);
        jPanel16.add(deviceField30);

        jPanel1.add(jPanel16);

        deviceField31.setIdentifier("");
        deviceField31.setLabelString("Node:");
        deviceField31.setNumCols(30);
        deviceField31.setOffsetNid(32);
        jPanel17.add(deviceField31);

        deviceField32.setIdentifier("");
        deviceField32.setLabelString("Stream name:");
        deviceField32.setNumCols(30);
        deviceField32.setOffsetNid(33);
        deviceField32.setTextOnly(true);
        jPanel17.add(deviceField32);

        jPanel1.add(jPanel17);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons deviceButtons1;
    private DeviceField deviceField1;
    private DeviceField deviceField10;
    private DeviceField deviceField11;
    private DeviceField deviceField12;
    private DeviceField deviceField13;
    private DeviceField deviceField14;
    private DeviceField deviceField15;
    private DeviceField deviceField16;
    private DeviceField deviceField17;
    private DeviceField deviceField18;
    private DeviceField deviceField19;
    private DeviceField deviceField2;
    private DeviceField deviceField20;
    private DeviceField deviceField21;
    private DeviceField deviceField22;
    private DeviceField deviceField23;
    private DeviceField deviceField24;
    private DeviceField deviceField25;
    private DeviceField deviceField26;
    private DeviceField deviceField27;
    private DeviceField deviceField28;
    private DeviceField deviceField29;
    private DeviceField deviceField3;
    private DeviceField deviceField30;
    private DeviceField deviceField31;
    private DeviceField deviceField32;
    private DeviceField deviceField4;
    private DeviceField deviceField5;
    private DeviceField deviceField6;
    private DeviceField deviceField7;
    private DeviceField deviceField8;
    private DeviceField deviceField9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
